FROM python:3.13-slim-bookworm

WORKDIR /app

RUN pip install "dapr-ext-drasi-dev==1.17.0.dev40"

COPY 02_durable_agent_smart_router.py 02_durable_agent_smart_router.py

CMD ["sh", "-c", "ls -l && python 02_durable_agent_smart_router.py"]
